<#noparse>server:
  port: 8081
spring:
  application:
    name: user
  profiles:
    active: dev
  devtools:
    add-properties: true
    livereload:
      port: 35002    
  datasource:
    driver-class-name: ${database.master.driver}
    url: ${database.master.url}
    username: ${database.master.username}
    password: ${database.master.password}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: false
management:
  endpoints:
    web:
      exposure:
        include: "info,health,actuator"
  endpoint:
    health:
      show-details: always
#
spring-doc:
  enable-spring-security: false
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.zhumingwu.project.controller
knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    #    description: "`我是测试`,**你知道吗**
    email: xiaoymin@foxmail.com
    concat: 八一菜刀
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
#    group:
#      test1:
#        group-name: 分组名称
#        api-rule: package
#        api-rule-resources:
#          - cn.zhumingwu.project.controller


project:
  register:
    host: localhost
    port: 8761
#    path: eureka
  swt:
    enable: true
    public-key: MCowBQYDK2VwAyEAOT01HtTg0VqZRMwToESQ+IPq4QFdMvRnQoAUECOwbJk=
    private-key: MC4CAQAwBQYDK2VwBCIEIO3PWBbNerow+QUh5KdN0Vyh9BTRCrStD7Gqa13U8knQ
    expired: 20m
    excludePaths:
      - /connect/**
      - /v3/**
      - /error
      - /**/*.html
      - /**/*.htm
      - /**/*.jpg
      - /**/*.png
      - /**/*.gif
      - /**/*.txt
      - /**/*.js
      - /**/*.ico
  swagger:
    enable: true
    basePackages:
      - cn.zhumingwu.project.controller
    group: users
    api-info:
      title: swagger api
      description: 优雅的restful风格
      terms-of-service-url: http://terms.zhumingwu.cn
      version: 1.0
      contact:
        name: zhumingwu
        url: https://www.zhumingwu.cn
        email: admin@zhumingwu.cn
logging:
  path: /var/log/${spring.application.name}-${server.port}
  level:
    web: INFO
    cn.zhumingwu: DEBUG
  pattern:
    console: '[%highlight(%-4level)] %msg%n'
</#noparse>